export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const FETCH_COURSES_REQUEST = " FETCH_COURSES_REQUEST";
export const FETCH_COURSES_SUCCESS = "  FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = " FETCH_COURSES_FAILURE";
export const FETCH_COURSE_DETAILS_SUCCESS = "  FETCH_COURSE_DETAILS_SUCCESS";
export const CREATE_COURSE_SUCCESS = " CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "  UPDATE_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "  DELETE_COURSE_SUCCESS";

export const FETCH_LESSONS_SUCCESS = "   FETCH_LESSONS_SUCCESS";
export const CREATE_LESSON_SUCCESS = "   CREATE_LESSON_SUCCESS";
export const DELETE_LESSON_SUCCESS = " DELETE_LESSON_SUCCESS";

export const FETCH_QUIZ_SUCCESS = "  FETCH_QUIZ_SUCCESS";
export const GENERATE_QUIZ_SUCCESS = "  GENERATE_QUIZ_SUCCESS";
export const FETCH_QUIZ_REQUEST = "  FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_FAILURE = "  FETCH_QUIZ_FAILURE";

export const FETCH_RESULTS_SUCCESS = " FETCH_RESULTS_SUCCESS";
export const SUBMIT_RESULT_SUCCESS = "  SUBMIT_RESULT_SUCCESS";
export const FETCH_RESULTS_REQUEST = " FETCH_RESULTS_REQUEST";
export const FETCH_RESULTS_FAILURE = " FETCH_RESULTS_FAILURE";
